import type {
  Client,
  ScanResult,
  PricingTier,
  MealEntry,
  DashboardMetrics,
} from '@/types';

// ─── Dashboard Metrics ─────────────────────────────────────────────
export const dashboardMetrics: DashboardMetrics = {
  active_clients: 14,
  urgent_alerts: 2,
  month_revenue_vnd: 21_000_000,
  time_saved_hours: 11.5,
};

// ─── Mock Client Roster ─────────────────────────────────────────────
export const mockClients: Client[] = [
  {
    id: 'c-001',
    name: 'Trần Minh Khoa',
    avatar_initial: 'TK',
    profile: { gender: 'male', age: 28, height_cm: 175, goal: 'recomp' },
    status: 'active',
    latest_biometrics: {
      weight_kg: 74.2,
      skeletal_muscle_mass_kg: 34.8,
      body_fat_mass_kg: 14.1,
      percent_body_fat: 19.0,
      total_body_water_liters: 45.2,
    },
    latest_nutrition: {
      bmr_kcal: 1722,
      tdee_kcal: 2368,
      target_calories_kcal: 2368,
      protein_grams: 163,
      carbohydrate_grams: 266,
      fat_grams: 66,
    },
    sessions_remaining: 18,
    sessions_total: 24,
    last_checkin: '2026-09-26',
    days_inactive: 0,
    weight_trend: -0.8,
    bf_trend: -1.2,
    compliance_score: 92,
  },
  {
    id: 'c-002',
    name: 'Lê Khánh Linh',
    avatar_initial: 'LL',
    profile: { gender: 'female', age: 25, height_cm: 160, goal: 'fat_loss' },
    status: 'active',
    latest_biometrics: {
      weight_kg: 58.5,
      skeletal_muscle_mass_kg: 21.4,
      body_fat_mass_kg: 18.2,
      percent_body_fat: 31.1,
      total_body_water_liters: 29.8,
    },
    latest_nutrition: {
      bmr_kcal: 1282,
      tdee_kcal: 1763,
      target_calories_kcal: 1410,
      protein_grams: 123,
      carbohydrate_grams: 141,
      fat_grams: 39,
    },
    sessions_remaining: 6,
    sessions_total: 24,
    last_checkin: '2026-09-25',
    days_inactive: 1,
    weight_trend: -1.8,
    bf_trend: -2.4,
    compliance_score: 88,
  },
  {
    id: 'c-003',
    name: 'Nguyễn Hoàng Nam',
    avatar_initial: 'NN',
    profile: { gender: 'male', age: 32, height_cm: 170, goal: 'muscle_gain' },
    status: 'warning',
    latest_biometrics: {
      weight_kg: 70.5,
      skeletal_muscle_mass_kg: 31.0,
      body_fat_mass_kg: 15.5,
      percent_body_fat: 22.0,
      total_body_water_liters: null,
    },
    latest_nutrition: {
      bmr_kcal: 1603,
      tdee_kcal: 2204,
      target_calories_kcal: 2645,
      protein_grams: 176,
      carbohydrate_grams: 331,
      fat_grams: 74,
    },
    sessions_remaining: 12,
    sessions_total: 24,
    last_checkin: '2026-09-22',
    days_inactive: 4,
    weight_trend: 0.3,
    bf_trend: 0.1,
    compliance_score: 45,
  },
  {
    id: 'c-004',
    name: 'Huỳnh Phát',
    avatar_initial: 'HP',
    profile: { gender: 'male', age: 26, height_cm: 178, goal: 'recomp' },
    status: 'active',
    latest_biometrics: {
      weight_kg: 82.1,
      skeletal_muscle_mass_kg: 38.2,
      body_fat_mass_kg: 16.8,
      percent_body_fat: 20.5,
      total_body_water_liters: 48.1,
    },
    latest_nutrition: {
      bmr_kcal: 1856,
      tdee_kcal: 2554,
      target_calories_kcal: 2554,
      protein_grams: 180,
      carbohydrate_grams: 287,
      fat_grams: 71,
    },
    sessions_remaining: 20,
    sessions_total: 24,
    last_checkin: '2026-09-26',
    days_inactive: 0,
    weight_trend: -0.4,
    bf_trend: -0.8,
    compliance_score: 95,
  },
  {
    id: 'c-005',
    name: 'Phạm Thanh Tùng',
    avatar_initial: 'PT',
    profile: { gender: 'male', age: 30, height_cm: 172, goal: 'fat_loss' },
    status: 'active',
    latest_biometrics: {
      weight_kg: 88.3,
      skeletal_muscle_mass_kg: 35.4,
      body_fat_mass_kg: 25.6,
      percent_body_fat: 29.0,
      total_body_water_liters: 44.2,
    },
    latest_nutrition: {
      bmr_kcal: 1780,
      tdee_kcal: 2448,
      target_calories_kcal: 1958,
      protein_grams: 177,
      carbohydrate_grams: 196,
      fat_grams: 54,
    },
    sessions_remaining: 15,
    sessions_total: 24,
    last_checkin: '2026-09-26',
    days_inactive: 0,
    weight_trend: -2.1,
    bf_trend: -1.9,
    compliance_score: 82,
  },
  {
    id: 'c-006',
    name: 'Võ Ngọc Hân',
    avatar_initial: 'VH',
    profile: { gender: 'female', age: 27, height_cm: 163, goal: 'fat_loss' },
    status: 'active',
    latest_biometrics: {
      weight_kg: 62.0,
      skeletal_muscle_mass_kg: 22.8,
      body_fat_mass_kg: 19.4,
      percent_body_fat: 31.3,
      total_body_water_liters: 31.2,
    },
    latest_nutrition: {
      bmr_kcal: 1340,
      tdee_kcal: 1843,
      target_calories_kcal: 1474,
      protein_grams: 124,
      carbohydrate_grams: 147,
      fat_grams: 41,
    },
    sessions_remaining: 10,
    sessions_total: 24,
    last_checkin: '2026-09-25',
    days_inactive: 1,
    weight_trend: -1.0,
    bf_trend: -1.5,
    compliance_score: 78,
  },
  {
    id: 'c-007',
    name: 'Đặng Quốc Bảo',
    avatar_initial: 'ĐB',
    profile: { gender: 'male', age: 35, height_cm: 168, goal: 'muscle_gain' },
    status: 'warning',
    latest_biometrics: {
      weight_kg: 65.4,
      skeletal_muscle_mass_kg: 28.6,
      body_fat_mass_kg: 12.2,
      percent_body_fat: 18.7,
      total_body_water_liters: 39.8,
    },
    latest_nutrition: {
      bmr_kcal: 1520,
      tdee_kcal: 2090,
      target_calories_kcal: 2508,
      protein_grams: 163,
      carbohydrate_grams: 314,
      fat_grams: 70,
    },
    sessions_remaining: 3,
    sessions_total: 24,
    last_checkin: '2026-09-23',
    days_inactive: 3,
    weight_trend: 0.6,
    bf_trend: -0.3,
    compliance_score: 52,
  },
  {
    id: 'c-008',
    name: 'Ngô Thị Mai',
    avatar_initial: 'NM',
    profile: { gender: 'female', age: 29, height_cm: 158, goal: 'recomp' },
    status: 'active',
    latest_biometrics: {
      weight_kg: 55.0,
      skeletal_muscle_mass_kg: 20.6,
      body_fat_mass_kg: 14.8,
      percent_body_fat: 26.9,
      total_body_water_liters: 28.4,
    },
    latest_nutrition: {
      bmr_kcal: 1240,
      tdee_kcal: 1705,
      target_calories_kcal: 1705,
      protein_grams: 110,
      carbohydrate_grams: 192,
      fat_grams: 57,
    },
    sessions_remaining: 16,
    sessions_total: 24,
    last_checkin: '2026-09-26',
    days_inactive: 0,
    weight_trend: -0.2,
    bf_trend: -0.7,
    compliance_score: 90,
  },
  {
    id: 'c-009',
    name: 'Bùi Văn Đức',
    avatar_initial: 'BĐ',
    profile: { gender: 'male', age: 24, height_cm: 180, goal: 'muscle_gain' },
    status: 'active',
    latest_biometrics: {
      weight_kg: 76.8,
      skeletal_muscle_mass_kg: 36.4,
      body_fat_mass_kg: 13.0,
      percent_body_fat: 16.9,
      total_body_water_liters: 47.0,
    },
    latest_nutrition: {
      bmr_kcal: 1810,
      tdee_kcal: 2489,
      target_calories_kcal: 2987,
      protein_grams: 192,
      carbohydrate_grams: 373,
      fat_grams: 83,
    },
    sessions_remaining: 22,
    sessions_total: 24,
    last_checkin: '2026-09-26',
    days_inactive: 0,
    weight_trend: 1.2,
    bf_trend: -0.5,
    compliance_score: 97,
  },
  {
    id: 'c-010',
    name: 'Trương Thị Yến',
    avatar_initial: 'TY',
    profile: { gender: 'female', age: 31, height_cm: 165, goal: 'fat_loss' },
    status: 'active',
    latest_biometrics: {
      weight_kg: 67.2,
      skeletal_muscle_mass_kg: 24.0,
      body_fat_mass_kg: 22.4,
      percent_body_fat: 33.3,
      total_body_water_liters: 32.6,
    },
    latest_nutrition: {
      bmr_kcal: 1398,
      tdee_kcal: 1923,
      target_calories_kcal: 1538,
      protein_grams: 134,
      carbohydrate_grams: 154,
      fat_grams: 43,
    },
    sessions_remaining: 8,
    sessions_total: 24,
    last_checkin: '2026-09-24',
    days_inactive: 2,
    weight_trend: -1.4,
    bf_trend: -1.8,
    compliance_score: 71,
  },
  {
    id: 'c-011',
    name: 'Lý Hoàng Anh',
    avatar_initial: 'LA',
    profile: { gender: 'male', age: 27, height_cm: 174, goal: 'recomp' },
    status: 'active',
    latest_biometrics: {
      weight_kg: 78.0,
      skeletal_muscle_mass_kg: 35.6,
      body_fat_mass_kg: 16.2,
      percent_body_fat: 20.8,
      total_body_water_liters: 46.0,
    },
    latest_nutrition: {
      bmr_kcal: 1768,
      tdee_kcal: 2431,
      target_calories_kcal: 2431,
      protein_grams: 171,
      carbohydrate_grams: 274,
      fat_grams: 68,
    },
    sessions_remaining: 14,
    sessions_total: 24,
    last_checkin: '2026-09-26',
    days_inactive: 0,
    weight_trend: -0.6,
    bf_trend: -1.0,
    compliance_score: 86,
  },
  {
    id: 'c-012',
    name: 'Đỗ Thị Hồng Nhung',
    avatar_initial: 'ĐN',
    profile: { gender: 'female', age: 23, height_cm: 155, goal: 'fat_loss' },
    status: 'active',
    latest_biometrics: {
      weight_kg: 52.3,
      skeletal_muscle_mass_kg: 19.2,
      body_fat_mass_kg: 15.8,
      percent_body_fat: 30.2,
      total_body_water_liters: 27.0,
    },
    latest_nutrition: {
      bmr_kcal: 1195,
      tdee_kcal: 1643,
      target_calories_kcal: 1314,
      protein_grams: 105,
      carbohydrate_grams: 131,
      fat_grams: 36,
    },
    sessions_remaining: 19,
    sessions_total: 24,
    last_checkin: '2026-09-26',
    days_inactive: 0,
    weight_trend: -1.1,
    bf_trend: -1.6,
    compliance_score: 84,
  },
  {
    id: 'c-013',
    name: 'Mai Xuân Trường',
    avatar_initial: 'MT',
    profile: { gender: 'male', age: 33, height_cm: 176, goal: 'fat_loss' },
    status: 'active',
    latest_biometrics: {
      weight_kg: 91.5,
      skeletal_muscle_mass_kg: 37.0,
      body_fat_mass_kg: 28.0,
      percent_body_fat: 30.6,
      total_body_water_liters: 46.8,
    },
    latest_nutrition: {
      bmr_kcal: 1840,
      tdee_kcal: 2530,
      target_calories_kcal: 2024,
      protein_grams: 183,
      carbohydrate_grams: 203,
      fat_grams: 56,
    },
    sessions_remaining: 11,
    sessions_total: 24,
    last_checkin: '2026-09-25',
    days_inactive: 1,
    weight_trend: -2.6,
    bf_trend: -2.0,
    compliance_score: 76,
  },
  {
    id: 'c-014',
    name: 'Hồ Thanh Thảo',
    avatar_initial: 'HT',
    profile: { gender: 'female', age: 26, height_cm: 162, goal: 'recomp' },
    status: 'active',
    latest_biometrics: {
      weight_kg: 57.8,
      skeletal_muscle_mass_kg: 22.0,
      body_fat_mass_kg: 15.0,
      percent_body_fat: 25.9,
      total_body_water_liters: 30.5,
    },
    latest_nutrition: {
      bmr_kcal: 1305,
      tdee_kcal: 1795,
      target_calories_kcal: 1795,
      protein_grams: 116,
      carbohydrate_grams: 202,
      fat_grams: 60,
    },
    sessions_remaining: 17,
    sessions_total: 24,
    last_checkin: '2026-09-26',
    days_inactive: 0,
    weight_trend: 0.2,
    bf_trend: -0.9,
    compliance_score: 91,
  },
];

// ─── OCR Scan Fixtures ──────────────────────────────────────────────
export const scanFixtures: ScanResult[] = [
  {
    fixture_name: 'InBody 270 — Male Recomp',
    client_profile: { gender: 'male', age: 28, height_cm: 175, goal: 'recomp' },
    biometrics: {
      weight_kg: 74.2,
      skeletal_muscle_mass_kg: 34.8,
      body_fat_mass_kg: 14.1,
      percent_body_fat: 19.0,
      total_body_water_liters: 45.2,
    },
    nutrition: {
      bmr_kcal: 1722,
      tdee_kcal: 2368,
      target_calories_kcal: 2368,
      protein_grams: 163,
      carbohydrate_grams: 266,
      fat_grams: 66,
    },
    confidence: 98,
    scanned_at: '2026-09-26T10:30:00+07:00',
  },
  {
    fixture_name: 'InBody 370 — Female Fat Loss',
    client_profile: { gender: 'female', age: 25, height_cm: 160, goal: 'fat_loss' },
    biometrics: {
      weight_kg: 58.5,
      skeletal_muscle_mass_kg: 21.4,
      body_fat_mass_kg: 18.2,
      percent_body_fat: 31.1,
      total_body_water_liters: 29.8,
    },
    nutrition: {
      bmr_kcal: 1282,
      tdee_kcal: 1763,
      target_calories_kcal: 1410,
      protein_grams: 123,
      carbohydrate_grams: 141,
      fat_grams: 39,
    },
    confidence: 96,
    scanned_at: '2026-09-26T11:15:00+07:00',
  },
  {
    fixture_name: 'Xiaomi Smart Scale — Male Fat Loss',
    client_profile: { gender: 'male', age: 30, height_cm: 170, goal: 'fat_loss' },
    biometrics: {
      weight_kg: 70.5,
      skeletal_muscle_mass_kg: 31.0,
      body_fat_mass_kg: 15.5,
      percent_body_fat: 22.0,
      total_body_water_liters: null,
    },
    nutrition: {
      bmr_kcal: 1603,
      tdee_kcal: 2204,
      target_calories_kcal: 1763,
      protein_grams: 155,
      carbohydrate_grams: 176,
      fat_grams: 49,
    },
    confidence: 94,
    scanned_at: '2026-09-26T14:45:00+07:00',
  },
];

// ─── Pricing Tiers ──────────────────────────────────────────────────
export const pricingTiers: PricingTier[] = [
  {
    name: 'Freemium',
    price_vnd: 0,
    price_label: '0 ₫',
    period: 'forever',
    features: [
      'Up to 3 active clients',
      '5 InBody scans / month',
      'Basic client roster',
      'Manual data entry',
      'Email support',
    ],
    cta_label: 'Start Free',
    highlighted: false,
  },
  {
    name: 'Pro Plan',
    price_vnd: 199_000,
    price_label: '199,000 ₫',
    period: '/month',
    badge: 'Most Popular',
    features: [
      'Unlimited active clients',
      'Unlimited InBody scans',
      'Smart PT Hub + Alerts',
      'Vietnamese macro engine',
      'Client PWA portal',
      'Priority Zalo support',
      'Advanced analytics',
    ],
    cta_label: 'Start 30-Day Free Trial',
    highlighted: true,
  },
  {
    name: 'Enterprise Studio',
    price_vnd: 1_500_000,
    price_label: '1,500,000 ₫',
    period: '/month',
    features: [
      'Everything in Pro',
      'Up to 5 trainer seats',
      'Multi-location management',
      'White-label client portal',
      'API access',
      'Dedicated account manager',
      'Custom onboarding',
    ],
    cta_label: 'Contact Sales',
    highlighted: false,
  },
];

// ─── Mock Meals for Trainee View ────────────────────────────────────
export const todayMeals: MealEntry[] = [
  {
    id: 'm-001',
    slot: 'breakfast',
    name: 'Phở bò tái nạm',
    calories: 480,
    protein: 28,
    carbs: 52,
    fat: 16,
    logged_at: '2026-09-26T07:30:00+07:00',
  },
  {
    id: 'm-002',
    slot: 'snack',
    name: 'Sữa chua Hy Lạp + Chuối',
    calories: 210,
    protein: 18,
    carbs: 22,
    fat: 6,
    logged_at: '2026-09-26T10:00:00+07:00',
  },
  {
    id: 'm-003',
    slot: 'lunch',
    name: 'Cơm tấm sườn bì chả',
    calories: 650,
    protein: 35,
    carbs: 68,
    fat: 24,
    logged_at: '2026-09-26T12:15:00+07:00',
  },
];
